name: socialoo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.0.0+3

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  video_player: ^2.2.3
  chewie: ^1.3.5
  flutter_datetime_picker: ^1.4.0
  intl:
  image_cropper: ^1.5.1
  image_picker: ^0.8.5+3
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  dio: ^4.0.6
  carousel_slider: ^4.1.1
  # carousel_pro: ^1.0.0
  country_code_picker: ^2.0.2
  async: ^2.4.1
  toast: ^0.3.0
  flutter_absolute_path: 
    git:
      url: https://github.com/canewsin/flutter_absolute_path.git
  path: ^1.7.0
  custom_refresh_indicator: ^1.2.1
  flutter_screenutil: ^5.5.3+2
  flutter_slidable: ^2.0.0
  giphy_get: ^2.0.4
  timeago: ^3.2.2
  inview_notifier_list: ^3.0.0
  path_provider: ^2.0.11
  image_gallery_saver: ^1.2.2
  permission_handler: ^10.0.0
  screenshot:
  dashed_circle: ^0.0.1
  google_fonts: ^3.0.1
  fluttertoast: ^8.0.9
  photofilters: ^3.0.1
  flutter_spinkit: ^5.1.0
  cloud_firestore: any
  firebase_auth: ^3.4.2
  firebase_database: ^9.0.19
  firebase_storage: ^10.3.2
  firebase_messaging: ^12.0.0
  photo_view: ^0.14.0
  convex_bottom_bar: ^3.0.0
  another_flushbar: ^1.10.20
  google_sign_in: ^5.4.0
  csc_picker: ^0.2.5
  flutter_image_compress: ^1.1.0
  linkable: ^3.0.1
  flutter_staggered_grid_view: ^0.4.0
  webview_flutter: ^2.0.12
  visibility_detector: ^0.3.3
  video_thumbnail:
    git: https://github.com/ajbcoder/video_thumbnail
  video_compress: ^3.0.0
  dynamic_themes:
  iconly: ^1.0.1
  nb_utils: ^4.6.16
  flutter_svg: ^1.1.1+1
  line_awesome_flutter: ^2.0.0
  adaptive_theme: ^3.1.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  ionicons: ^0.1.2
  share: ^2.0.4
  flutter_reaction_button: ^2.0.0+1
  google_mobile_ads: ^2.0.1
  filesize: ^2.0.1
  file_picker: ^4.6.1
  flutter_pdfview: ^1.2.2
  # geolocator: ^6.2.1
  geocoding: ^2.0.4
  collection: ^1.15.0-nullsafety.4
  http: ^0.13.5
  card_swiper: ^2.0.4
  # add by irshad
#  validators: ^3.0.0
  razorpay_flutter: ^1.3.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "assets/images/appicon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/video/


  fonts:
    
    - family: Helvetica  
      fonts:
        - asset: assets/fonts/Helvetica neue.ttf

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf 

    - family: BrushScript
      fonts:
        - asset: assets/fonts/brushScript.ttf  

    - family: icomoon
      fonts:
      - asset: assets/fonts/IcoMoon.ttf    

    - family: SpaceGrotesk
      fonts:
      - asset: assets/fonts/SpaceGrotesk-Bold.ttf 


  